a, b = input().split()
plus = int(a)+int(b)
minus = int(a)-int(b)
mult = int(a)*int(b)
div = int(a)//int(b)
rem = int(a)%int(b)
divi = float(a)/float(b)
print(plus)
print(minus)
print(mult)
print(div)
print(rem)
print(format(divi, ".2f"))